is it now

diff --git a/.github/workflows/upade_taktile_nodes.yml b/.github/workflows/upade_taktile_nodes.yml
--- a/.github/workflows/upade_taktile_nodes.yml
+++ b/.github/workflows/upade_taktile_nodes.yml
@@ -38,11 +38,10 @@ jobs:
           # check API response 
           call_status=$(jq -c '.status' flow_res.json)
           echo $call_status
-          if [ $call_status != success ] 
-            then
-              status_msg=$(jq -c '.detail.msg' flow_res.json)
-              echo "Call not successful. Status:error Message: $status_msg" 
-              exit 1
+          if [ $call_status != "success" ]; then
+            status_msg=$(jq -c '.detail.msg' flow_res.json)
+            echo "Call not successful. Status:error Message: $status_msg" 
+            exit 1
           fi
           api_msg=$(jq '.data.message' flow_res.json)
           echo "API call with status: $call_status; Message: $api_msg"
